"""LLM Provider abstraction for Unsloth and other models."""
from abc import ABC, abstractmethod
from typing import Optional, Dict, Any
import logging

logger = logging.getLogger(__name__)


class LLMProvider(ABC):
    """Abstract base class for LLM providers."""

    @abstractmethod
    async def generate(self, prompt: str, max_tokens: int = 1024) -> str:
        """Generate text from prompt."""
        pass

    @abstractmethod
    async def initialize(self) -> None:
        """Initialize the provider."""
        pass

    @abstractmethod
    async def shutdown(self) -> None:
        """Shutdown the provider."""
        pass


class UnslothProvider(LLMProvider):
    """Unsloth-based LLM provider."""

    def __init__(
        self,
        model_name: str = "meta-llama/Llama-2-7b-hf",
        max_tokens: int = 1024,
        temperature: float = 0.7,
    ):
        self.model_name = model_name
        self.max_tokens = max_tokens
        self.temperature = temperature
        self.model = None
        self.tokenizer = None
        self._initialized = False

    async def initialize(self) -> None:
        """Initialize Unsloth model."""
        try:
            from unsloth import FastLanguageModel

            logger.info(f"Loading Unsloth model: {self.model_name}")

            self.model, self.tokenizer = FastLanguageModel.from_pretrained(
                model_name=self.model_name,
                max_seq_length=self.max_tokens,
                dtype=None,  # Auto-detect
                load_in_4bit=True,  # Use 4-bit quantization for memory efficiency
            )

            # Prepare for inference
            FastLanguageModel.for_inference(self.model)
            self._initialized = True
            logger.info("Unsloth model initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize Unsloth model: {e}")
            raise

    async def generate(self, prompt: str, max_tokens: int = 1024) -> str:
        """Generate text using Unsloth model."""
        if not self._initialized:
            raise RuntimeError("Provider not initialized. Call initialize() first.")

        try:
            inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=max_tokens,
                temperature=self.temperature,
                top_p=0.95,
                do_sample=True,
            )
            response = self.tokenizer.decode(
                outputs[0], skip_special_tokens=True, max_new_tokens=max_tokens
            )
            # Remove the prompt from response
            return response[len(prompt) :].strip()
        except Exception as e:
            logger.error(f"Error generating text: {e}")
            raise

    async def shutdown(self) -> None:
        """Shutdown and cleanup."""
        self.model = None
        self.tokenizer = None
        self._initialized = False
        logger.info("Unsloth provider shutdown")


class MockProvider(LLMProvider):
    """Mock LLM provider for testing and development."""

    def __init__(self):
        self._initialized = False
        self.responses = {
            "cube": "A cube is a 3D shape with 6 equal square faces. To create one, you need 3D modeling software or use parametric design with dimensions: 100x100x100mm.",
            "default": "This is a mock response for testing. In production, this would be generated by the actual LLM model.",
        }

    async def initialize(self) -> None:
        """Initialize mock provider."""
        logger.info("Mock LLM provider initialized")
        self._initialized = True

    async def generate(self, prompt: str, max_tokens: int = 1024) -> str:
        """Generate mock response."""
        if not self._initialized:
            raise RuntimeError("Provider not initialized. Call initialize() first.")

        # Simple mock logic - check for keywords
        prompt_lower = prompt.lower()
        for key, response in self.responses.items():
            if key in prompt_lower:
                return response

        return self.responses["default"]

    async def shutdown(self) -> None:
        """Shutdown mock provider."""
        self._initialized = False
        logger.info("Mock provider shutdown")


class LLMProviderFactory:
    """Factory for creating LLM providers."""

    _providers = {
        "unsloth": UnslothProvider,
        "mock": MockProvider,
    }

    @staticmethod
    def create(
        provider_type: str = "mock",
        model_name: str = "meta-llama/Llama-2-7b-hf",
        **kwargs,
    ) -> LLMProvider:
        """Create LLM provider instance."""
        provider_class = LLMProviderFactory._providers.get(
            provider_type.lower(), MockProvider
        )

        if provider_type.lower() == "unsloth":
            return provider_class(model_name=model_name, **kwargs)
        return provider_class()

    @staticmethod
    def register_provider(name: str, provider_class: type) -> None:
        """Register custom provider."""
        LLMProviderFactory._providers[name.lower()] = provider_class
